Openarl/PathOfBuilding

- Data/Gems/act_dex.lua
Ice Shot and Frost Blades Physical to Cold conversion increased to 60%
> Updated Ice Shot and Frost Blades to 60% Conv

- CONTRIBUTING.md
Just a little gem I found in the source while working on #669.
> Added note about rebuilding the mod cache

- Classes/ImportTab.lua
Solves errors of Unsupported protocol: " https://"
Signed-off-by: Philippe Pepos Petitclerc <ppeposp@gmail.com>
> Trim Pastebin URL before downloading.

- Data/Uniques/shield.lua
Add the description Trigger Level 20 Fog of War when your Trap is triggered to the current variant of Kongming.
This closes #1193
> Corrected description of Kongming's current variant

- Data/Uniques/dagger.lua
> changed lvl req for sanguine gambol

- Data/3_0/Skills/act_int.lua
- Export/Skills/act_int.txt
> skills: add radius (20) to vortex

- Modules/ModParser-3_0.lua
Add parsing for the new elemental / chaos dual resist mods
> add 3.5 elemental / chaos dual resists

- Data/New.lua
Added known Synthesis uniques.
> Add Synthesis uniques

- Data/New.lua
Added 2 more Synthesis uniques.
> Add missing uniques

- Data/3_0/Skills/act_str.lua
- Export/Skills/act_str.txt
I copied this from the base skill, is there a way to verify that it's the same radius?
> skills: add radius to vaal earthquake

- Modules/ModParser-3_0.lua
Coated Shrapnel has a new type of mod that grants all passive skills in radius extra stats.
> Added support for new type of mod on Coated Shrapnel in 3.8.0

- Data/Uniques/sword.lua
> Correct mod on Edge of Madness

- Data/Uniques/boots.lua
- Modules/CalcTools.lua
- Modules/ModParser-3_0.lua
Bones of Ullr has no new variant. Also added support for its new type of mod ("+# to level of all $gem_name gems").
> Updated Bones of Ullr to 3.8.0

- Data/Uniques/ring.lua
Berek's Grip now has a new variant.
> Updated Berek's Grip to 3.8.0

- Data/Uniques/gloves.lua
Blasphemer's Grasp has no new variant.
> Updated Blasphemer's Grasp to 3.8.0

- Data/Uniques/wand.lua
Midnight Bargain now has a new variant.
> Updated Midnight Bargain to 3.8.0

- Data/Uniques/jewel.lua
Healthy Mind is now limited to 1.
> Updated Healthy Mind to 3.8.0

- Data/Uniques/body.lua
Vis Mortis now has a new variant.
> Updated Vis Mortis to 3.8.0

- Data/Uniques/wand.lua
Ashcaller now has a legacy variant.
> Updated Ashcaller to 3.8.0

- Data/Uniques/shield.lua
Corrects the increased armour roll on Magna Eclipsis. #1395 #1605
> Correct mod on Magna Eclipsis.

- Data/Uniques/helmet.lua
Corrects the fire resistance roll on Memory Vault.
> Correct mod on Memory Vault.

- Classes/PassiveTree.lua
Fixing the bug mentioned in #1725
>  Fix passive tree coordinate calculation

- Data/Uniques/staff.lua
I hope I'm doing this correctly!
> Update "Femurs of the Saints" to 3.8.0 staff.lua

- Modules/ModParser-3_0.lua
At some point, these mods got reworded in such a way that they need to be parsed manually.
> Added support for "warcried recently"

- Data/Uniques/body.lua
- Data/Uniques/bow.lua
- Data/Uniques/gloves.lua
- Data/Uniques/helmet.lua
- Data/Uniques/jewel.lua
- Data/Uniques/ring.lua
Updated all uniques that got balance changes in 3.9.0
> Updated all uniques rebalanced in 3.9.0

- Data/Uniques/belt.lua
- Modules/ModParser-3_0.lua
Fixes #1809. Also, @Openarl, I've amended #1764 since your last comment, which is referenced by #1809, as well as #1762 and #1787.
> Patch 3.9.0 mod on Dyadian Dawn reworded

- Data/Uniques/jewel.lua
- Modules/ModParser-3_0.lua
They both have a new variant. Updated Mods on jewels and removed old wordings.
> Updated Tempered and Transcendent Jewels to 3.8.0

- Modules/ModParser-3_0.lua
Added support for reworded "per Totem" stat, which is now "for each Summoned Totem".
> Updated totem multiplier mod to 3.9.0

- Modules/ConfigOptions.lua
Change config for new value in 3.9
> Update boss Res Value (3.9)
