Data/Bases/sword.lua

They were still using the old values for the implicits (2% and 3%  instead of 4% and 6%). Curiously, I'm not sure when GGG doubled the value of these implicits since it seems to not have been documented.

Update % dodge chance on Hook/Grappler swords

---

Classes/ImportTab.lua

Right now every build shared with pastebin links is publicly announced on the pastebin recent pastes, some users might be uncomfortable with this, I think unlisted is a better default.

Pastebin links unlisted instead of public.

---

Classes/PassiveTreeView.lua

Simple but effective optimisation for the PassiveTreeView, caching the search results saves several thousand calls of string.match() which were quite expensive.
Storing the previous string used isn't the neatest solution but I think it's the most error resistant. Alternatives include:
- A boolean searchStrNeedsChecking, which requires the anyone who sets searchStr to set that too.
- The same flag with a SetSearchStr(str) function to set it for you, but you'd still need to remember to call the setter instead of setting it directly (Lua doesn't do private variables).
- Use the function above and iterate over the nodes in that function rather than doing it later, which risks multiple calls in the same frame causing spikes, and you'd probably still have to store the string somewhere so you …

Optimisation for PassiveTreeView: cache the search results.

---

Data/Uniques/ring.lua

Resulting in not displaying inc fire damage for variant 2. Closes #673

Fixed typo in bereks pass variant identifier

---

Classes/ConfigTab.lua

Closes feature request #604
This was already considered if the main skill was a movement skill. In many scenarios the main skill is not a movement skill. This is also more transparent since (I at least) didn't even know that this was considered if and only if the movement skill was also main skill.

Added checkbox for used movement skill recently

---

Classes/PassiveTreeView.lua

This is the only optimisation I found that provides reasonable gains without confusing the code too much.  TreeToScreen is used so frequently that caching the results some basic arithmatic saves about 2% of the frame time.

Minor optimisation for PassiveTreeView

---

Modules/CalcActiveSkill.lua

Currently if you input values >100 PoB crashes, this is fixed by adding a manual clamp.
Error:
Demo POB:
https://pastebin.com/Huxk6vhW - crashes on the master branch on import, works fine in the dev mode with the fix below.

Added a clamp to the minion level in calcactive skill [1, minion.levell, 100]

---

Data/Uniques/quiver.lua
Modules/ModParser-3_0.lua

Hi. PoB is a very useful tool. I always have fun. :)
- Can parse `Arrows deal 50% increased Damage with Hits and Ailments to Targets they Pierce`
- Remove special mod from `specialModList`
- Fix unique item Drillneck special modifier
- https://pathofexile.gamepedia.com/Drillneck
---
1. PoB 1.4.74 Uniques Drillneck modifier was incorrect
- on https://github.com/Openarl/PathOfBuilding/blob/master/Data/Uniques/quiver.lua#L67
- `{variant:2}Arrows deal 50% increased Damage against Pierced Targets`
- PoB 1.4.74 can parse this
2. Actually imported from the game
- `Arrows deal 50% increased Damage with Hits and Ailments to Targets they Pierce`
- PoB 1.4.74 can't parse this
Build data for test: https://pastebin.com/856uV0gb
- Include item: PoB 1.4.74 Uniques Drillneck (can parse / backward …

Support Drillneck special modifier.

---

Modules/ModParser-3_0.lua

"you have onslaught while not on low mana" had its condition flipped

Fix Dance of the Offered, Omeyocan

---

Data/Uniques/body.lua

#1130 
Crystal vault does not have the property 'Cannot be frozen', removed
https://pathofexile.gamepedia.com/Crystal_Vault

removed cannot be frozen from crystal vault

---

Data/New.lua

- Added
- Aul's Uprising variants
- Doryani's Delusion variants
- Hale Negator variant
- Delve rings used in Precursor's Emblem recipe
- String of Servitude
- league and drop information
- Updated
- order of mods
- value ranges of mods
- some specific mods wording
- I've used the trade search, wiki and poedb (in order of credibility) as sources of information
- Precursor's Emblem can't be implemented because:
- The current system of variants needs to be improved. It doesn't support Watcher's Eye with 3 mods and even increasing the number of selectable mods doesn't solve all problems. For example, depending on the item base, Precursor's Emblem can have 2 power charge mods and 1 endurance charge mod. It would need some kind of variant grouping to work correctly.

Update Incursion and Delve uniques

---

Modules/ModParser-3_0.lua

- x Life Regenerated per second for each Uncorrupted Item Equipped
- x to Total Mana Cost of Skills for each Corrupted Item Equipped

Support Vivinsect mods

---

Modules/ConfigOptions.lua
Modules/ModParser-3_0.lua

New config option
- "Is the enemy on consecrated ground?". Will displayed at all times in Effective DPS. I can flag it if you want.
New mods
- +2% to Critical Strike Chance against Enemies on Consecrated ground during Effect
- Enemies on Consecrated Ground you create during Effect take 10% increased Damage

Add mods from Bottle Faith, Sulphur Flask

---

Modules/ConfigOptions.lua

Lowered the curse effect on normal bosses and shaper according to:
> Bosses which previously had 60% or 80% less effect of curses on them now have 33% or 66% less effect of curses on them respectively. This includes map bosses, Incursion architects, Betrayal targets, Breachlords, Shaper, Elder and others.

Update curse effect on bosses

---

.gitignore

Added crit cap changes from patch 3.6(working on some more stuff, but because I'll also implement stuff that's not completely datamined yet I'll try to keep the branches and pull requests separated and only make pull requests for stuff that's actually confirmed and not "half-data like gem damage")

Crit cap changes

---

Data/New.lua

Added 4 missing Synthesis uniques. Maloney's Mechanism has a new base type so it won't show until item data gets updated.

Add missing Synthesis uniques

---

Data/Uniques/helmet.lua

Current version of Bringer of Rain still has the 6% block chance.

Added block chance to Bringer of Rain

---

Data/Uniques/staff.lua

Tremor Rod now has a new variant. Remote Mine got renamed to Blastchain Mine.

Updated Tremor Rod to 3.8.0

---

Data/Uniques/shield.lua

Jaws of Agony now grants a level 25 Bear Trap skill. No new variant is introduced. Old versions will say it only grants a level 20 Bear Trap; this is only visual.

Updated Jaws of Agony to 3.8.0

---

Data/Uniques/amulet.lua

Sidhebreath now has a new variant. It also loses its "Minions deal (10-15)% increased Damage" mod, which is missing from the patch notes.

Updated Sidhebreath to 3.8.0

---

Data/Uniques/amulet.lua

Star of Wraeclast's unique skill Illusory Warp gets replaced by Frostblink in new versions.

Updated Star of Wraeclast to 3.8.0

---

Data/Uniques/dagger.lua
Data/Uniques/staff.lua

These items now affect all spells of certain types, rather than just those socketed in the item. Closes issue #1682 Related PR: #1736

Updated some uniques to 3.8.0 to grant +# global spell skill gem levels

---

Data/Uniques/sword.lua

Updated Queen's Decree/Escape minion modifiers:
- minions deal (30-40%) increased damage
- minions have (30-40) increased maximum life
The current master runs on 10-15 values for both items, which are not correct.

Updated Queen's Decree/Escape minion modifiers

---

Data/Uniques/staff.lua

Agnerod staves give "+# to Level of all Lightning Spell Skill Gems"

Agnerod global +level to gems

---

Data/Uniques/ring.lua

In 3.8.0, the implicit on Paua Rings was changed. While rare Paua Rings are already updated, uniques are not. There is no legacy variant.

Correct implicit on all unique Paua Rings.

---

Data/Uniques/boots.lua

Ingame, it says "Triggers" instead of "Casts". Besides, the expected behavior of items that grant abilities in Path of Building is to have an empty nameSpec attribute. In it's current form, this mod breaks some of my code.

Correct mod on Abberath's Hooves.

---

Modules/ModParser-3_0.lua

The buff effect of buffs granted by "Ancestral" totems was implemented incorrectly, causing all buffs to be scaled by it.

Correctly implemented new mod on Panopticon

---

Modules/CalcOffence-3_0.lua
Modules/ModParser-3_0.lua

Note that it is currently not possible to add "Enemies have -X% to Total Physical Damage Reduction against your Hits", as whether a skill can impale is only determined after enemy defense calculations are completed.

Added support for "Enemies have -X% to Total Physical Damage Reduction against your Hits"

---

Classes/ConfigTab.lua
Modules/ConfigOptions.lua

Added support for this modifier that is found on Berserker's War Bringer ascendancy node. As having warcried recently (the last 4 seconds) also implies having warcried in the past 8 seconds and "conditionUserWarcryRecently" already has the implyCond "UsedSkillRecently", I've also implemented support for multiple implied conditions in the form of a parameter implyCondList.

Added support for "if you've Warcried in the past 8 seconds"
